"""
Cross-scene retrieval assistant — Extensions PRD §8 (F5).

Answers recall and aggregate questions spanning every scene the workspace has
analysed: "which locations have I inspected?", "how many bi-temporal pairs?",
"what did I find in Pune?".

Two hard rules, both inherited from v1 §9.6:

* **No new source of truth.** Every fact comes from the `scenes`, `queries` and
  `traces` collections. This module never writes one.
* **Every number is traceable.** Aggregate figures are computed here in Python
  from those rows, not generated by the model. The model is given a retrieved
  context block and told to answer only from it; each answer carries the scene
  ids it drew on so a reader can click through and check.

Retrieval is lexical (token overlap + field boosts), not embedding-based. On a
workspace of hundreds of scenes that is both sufficient and offline-capable;
swapping in embeddings later changes this file only.
"""

from __future__ import annotations

import logging
import re
from typing import Any, Dict, List, Optional, Tuple

log = logging.getLogger(__name__)

# Words that carry no discriminating signal in this corpus.
_STOP = {
    "the", "a", "an", "of", "in", "on", "at", "to", "for", "and", "or", "is",
    "are", "was", "were", "what", "which", "how", "many", "much", "show", "me",
    "my", "i", "have", "has", "did", "do", "does", "any", "all", "list", "tell",
    "about", "with", "from", "scene", "scenes", "image", "images",
}

_TOKEN_RE = re.compile(r"[a-z0-9_]+")


def _tokens(text: str) -> List[str]:
    return [t for t in _TOKEN_RE.findall((text or "").lower()) if t not in _STOP and len(t) > 1]


# ---------------------------------------------------------------------------
# Corpus
# ---------------------------------------------------------------------------
def build_corpus(db) -> List[Dict[str, Any]]:
    """
    One retrievable document per scene, enriched with the queries asked against
    it. Nothing is fabricated: a field is omitted when the underlying row does
    not have it.
    """
    from core.geo.admin_lookup import get_admin_lookup

    scenes = db.list_documents("scenes") or []
    queries = db.list_documents("queries") or []
    lookup = get_admin_lookup()

    by_scene: Dict[str, List[Dict[str, Any]]] = {}
    for q in queries:
        by_scene.setdefault(q.get("scene_id"), []).append(q)

    corpus: List[Dict[str, Any]] = []
    for sc in scenes:
        sid = sc.get("id")
        imgs = sc.get("images") or []
        qs = by_scene.get(sid, [])

        bounds = None
        acquired: List[str] = []
        for im in imgs:
            meta = im.get("metadata") or {}
            if bounds is None and meta.get("bounds_wgs84"):
                bounds = meta["bounds_wgs84"]
            if im.get("acquired_at"):
                acquired.append(im["acquired_at"])

        # Resolve the place name the same way the analytics dashboard does,
        # so the assistant and the charts never disagree about where a scene is.
        place = None
        if bounds and len(bounds) == 4:
            unit = lookup.label_for((bounds[0] + bounds[2]) / 2.0,
                                    (bounds[1] + bounds[3]) / 2.0)
            if unit:
                place = f"{unit.district}, {unit.state}"

        answers = [q.get("answer") or "" for q in qs]
        doc = {
            "scene_id": sid,
            "name": sc.get("name") or sid,
            "input_config": sc.get("input_config"),
            "modalities": sc.get("modalities") or [],
            "created_at": sc.get("created_at"),
            "bounds_wgs84": bounds,
            "place": place,
            "acquired_dates": sorted(acquired),
            "query_count": len(qs),
            "queries": [q.get("query") or "" for q in qs],
            "answers": answers,
            "confidences": [
                (q.get("confidence") or {}).get("value")
                for q in qs
                if isinstance(q.get("confidence"), dict)
            ],
        }
        doc["_text"] = " ".join(
            [
                str(doc["name"]),
                str(doc["input_config"] or ""),
                str(doc["place"] or ""),
                " ".join(doc["modalities"]),
                " ".join(doc["queries"]),
                " ".join(answers),
            ]
        )
        corpus.append(doc)

    return corpus


def retrieve(corpus: List[Dict[str, Any]], question: str, k: int = 6) -> List[Dict[str, Any]]:
    """Rank scenes by lexical overlap with the question. Name matches count double."""
    q_tokens = set(_tokens(question))
    if not q_tokens:
        # No usable query terms — most recent scenes are the honest default.
        return sorted(corpus, key=lambda d: d.get("created_at") or "", reverse=True)[:k]

    scored: List[Tuple[float, Dict[str, Any]]] = []
    for doc in corpus:
        body = set(_tokens(doc["_text"]))
        name = set(_tokens(str(doc["name"])))
        if not body:
            continue
        overlap = len(q_tokens & body) + len(q_tokens & name)
        if overlap:
            scored.append((overlap / (len(q_tokens) + 1), doc))

    scored.sort(key=lambda p: p[0], reverse=True)
    hits = [d for _, d in scored[:k]]

    # Backfill with the most recent scenes the query did not match. A broad
    # question ("summarise everything I've analysed") has almost no lexical
    # overlap with any single scene, and answering it from two matched rows
    # while fourteen sit unread is a retrieval failure, not a short answer.
    if len(hits) < k:
        seen = {d["scene_id"] for d in hits}
        recent = sorted(corpus, key=lambda d: d.get("created_at") or "", reverse=True)
        hits += [d for d in recent if d["scene_id"] not in seen][: k - len(hits)]
    return hits


# ---------------------------------------------------------------------------
# Aggregates — computed here, never asked of the model
# ---------------------------------------------------------------------------
def compute_aggregates(corpus: List[Dict[str, Any]]) -> Dict[str, Any]:
    confs = [c for d in corpus for c in d["confidences"] if isinstance(c, (int, float))]
    by_config: Dict[str, int] = {}
    for d in corpus:
        key = d.get("input_config") or "UNKNOWN"
        by_config[key] = by_config.get(key, 0) + 1

    georeferenced = [d for d in corpus if d.get("bounds_wgs84")]
    return {
        "scene_count": len(corpus),
        "query_count": sum(d["query_count"] for d in corpus),
        "by_input_config": by_config,
        "georeferenced_scenes": len(georeferenced),
        "mean_confidence": round(sum(confs) / len(confs), 3) if confs else None,
    }


# A roster line is ~90 characters, so the cap is about 18k characters of
# context — comfortable for every backend, and far beyond a realistic workspace.
ROSTER_LIMIT = 200


def render_context(
    hits: List[Dict[str, Any]],
    aggregates: Dict[str, Any],
    corpus: Optional[List[Dict[str, Any]]] = None,
) -> str:
    """
    The retrieved block handed to the model. Only rows, no interpretation.

    Two tiers: a complete roster of every scene (terse — enough to answer
    "which places have I looked at?") and full detail for the top-k retrieved
    scenes. Without the roster the model can only speak about what retrieval
    happened to surface, which reads as though the other scenes do not exist.
    """
    lines = ["WORKSPACE TOTALS (computed from stored rows):"]
    lines.append(f"- scenes: {aggregates['scene_count']}")
    lines.append(f"- queries answered: {aggregates['query_count']}")
    lines.append(f"- georeferenced scenes: {aggregates['georeferenced_scenes']}")
    if aggregates["mean_confidence"] is not None:
        lines.append(f"- mean confidence: {aggregates['mean_confidence']}")
    for cfg, n in sorted(aggregates["by_input_config"].items()):
        lines.append(f"- {cfg}: {n}")

    if corpus:
        lines.append("")
        lines.append(
            f"ALL SCENES IN THIS WORKSPACE ({len(corpus)}; complete list, "
            "one line each. Use this to answer questions about which "
            "scenes or places exist):"
        )
        roster = sorted(corpus, key=lambda d: d.get("created_at") or "", reverse=True)
        for d in roster[:ROSTER_LIMIT]:
            centre = ""
            if d.get("bounds_wgs84"):
                b = d["bounds_wgs84"]
                where = d.get("place") or "centre"
                centre = f", {where} {(b[1] + b[3]) / 2:.4f} {(b[0] + b[2]) / 2:.4f}"
            dates = (", acquired " + "/".join(d["acquired_dates"])
                     if d.get("acquired_dates") else "")
            lines.append(
                f"- [{d['scene_id']}] {d['name']} ({d['input_config']}"
                f"{centre}{dates}, {d['query_count']} queries)"
            )
        if len(roster) > ROSTER_LIMIT:
            lines.append(
                f"- ...and {len(roster) - ROSTER_LIMIT} older scenes not listed. "
                "Say so if the user asks for a complete list."
            )

    lines.append("")
    lines.append("DETAIL FOR THE MOST RELEVANT SCENES:")
    for d in hits:
        lines.append(f"\n[{d['scene_id']}] {d['name']}")
        lines.append(f"  config: {d['input_config']}  modalities: {', '.join(d['modalities'])}")
        if d.get("bounds_wgs84"):
            b = d["bounds_wgs84"]
            lines.append(
                f"  bounds WGS84: W {b[0]:.4f}, S {b[1]:.4f}, E {b[2]:.4f}, N {b[3]:.4f}"
            )
            if d.get("place"):
                lines.append(f"  place: {d['place']}")
        else:
            lines.append("  bounds: not georeferenced")
        if d.get("acquired_dates"):
            lines.append(f"  acquisition dates: {', '.join(d['acquired_dates'])}")
        lines.append(f"  queries asked: {d['query_count']}")
        for q, a in list(zip(d["queries"], d["answers"]))[:3]:
            if q:
                lines.append(f"    Q: {q}")
            if a:
                lines.append(f"    A: {a[:280]}")
    return "\n".join(lines)


SYSTEM = """You are the SatQuery workspace assistant. You answer questions about
the remote-sensing scenes this workspace has already analysed.

Answer ONLY from the CONTEXT block supplied to you. It contains totals computed
directly from the database and rows for the most relevant scenes.

Rules:
- Never invent a scene, a location, a date, or a number. If the context does not
  contain the answer, say so plainly and name what is missing.
- Totals in the context are authoritative. Do not recompute or estimate them.
- Refer to scenes by their name and cite the bracketed scene id, e.g. [scene_123].
- Be concise. Prefer a short list over a paragraph when the answer is a set.
"""


async def answer_question(
    db,
    question: str,
    vlm_backend: Optional[str] = None,
    k: int = 6,
) -> Dict[str, Any]:
    """
    Answer a cross-scene question.

    Returns the answer plus the scene ids it was grounded in, and the computed
    aggregates so the caller can render figures without trusting the prose.
    """
    corpus = build_corpus(db)
    aggregates = compute_aggregates(corpus)

    if not corpus:
        return {
            "answer": (
                "This workspace has no scenes yet, so there is nothing to search. "
                "Upload imagery and the assistant will be able to answer questions "
                "across it."
            ),
            "citations": [],
            "aggregates": aggregates,
            "grounded": True,
        }

    hits = retrieve(corpus, question, k=k)
    context = render_context(hits, aggregates, corpus)

    from services.inference.vlm_gateway import (
        VLMUnavailable, llm_text_call, vlm_available,
    )

    ok, reason = vlm_available(vlm_backend)
    if not ok:
        # Degrade to a deterministic summary rather than refusing outright —
        # the totals are real and useful even with no model available.
        return {
            "answer": _deterministic_answer(hits, aggregates, reason),
            "citations": [d["scene_id"] for d in hits],
            "aggregates": aggregates,
            "grounded": True,
            "degraded": True,
            "reason": reason,
        }

    prompt = f"CONTEXT\n{context}\n\nQUESTION\n{question}"
    try:
        out = await llm_text_call(prompt, SYSTEM, backend=vlm_backend or "vertex")
    except VLMUnavailable as e:
        return {
            "answer": _deterministic_answer(hits, aggregates, str(e)),
            "citations": [d["scene_id"] for d in hits],
            "aggregates": aggregates,
            "grounded": True,
            "degraded": True,
            "reason": str(e),
        }
    except Exception as e:  # noqa: BLE001
        return {
            "answer": _deterministic_answer(hits, aggregates, f"{type(e).__name__}: {e}"),
            "citations": [d["scene_id"] for d in hits],
            "aggregates": aggregates,
            "grounded": True,
            "degraded": True,
            "reason": f"{type(e).__name__}: {e}",
        }

    return {
        "answer": out.get("text") or "",
        "citations": [d["scene_id"] for d in hits],
        "aggregates": aggregates,
        "grounded": True,
        "model": f"{out.get('backend')}:{out.get('model')}",
    }


def _deterministic_answer(
    hits: List[Dict[str, Any]], aggregates: Dict[str, Any], reason: str
) -> str:
    """Offline fallback: real rows, plainly stated, no model involved."""
    parts = [
        f"The assistant's language model is unavailable ({reason}), so here are the "
        "matching records directly:",
        "",
        f"- {aggregates['scene_count']} scenes, {aggregates['query_count']} queries answered.",
    ]
    if aggregates["mean_confidence"] is not None:
        parts.append(f"- Mean confidence across those queries: {aggregates['mean_confidence']}.")
    parts.append("")
    parts.append("Most relevant scenes:")
    for d in hits[:5]:
        loc = ""
        if d.get("bounds_wgs84"):
            b = d["bounds_wgs84"]
            loc = f" — centred near {(b[1] + b[3]) / 2:.3f}, {(b[0] + b[2]) / 2:.3f}"
        parts.append(f"- {d['name']} [{d['scene_id']}], {d['input_config']}{loc}")
    return "\n".join(parts)
