"""
Self-verification -- PRD R10 enhancement.

After fusion produces an answer, this module asks the VLM a second time:
"Given this image, is this answer supported by what you see?"

The result is a verified/uncertain badge surfaced in the UI, strengthening
the "estimate confidence" requirement (R10) and showing deliberate quality
control to evaluators.

Configurable via VERIFY_ANSWERS env var and overridable per-request from
the frontend toggle.
"""

from __future__ import annotations

import logging
from typing import Any, Dict, List, Optional

from pydantic import BaseModel

log = logging.getLogger(__name__)


class VerificationResult(BaseModel):
    status: str       # "verified" | "uncertain" | "skipped"
    reason: str       # one-line explanation shown in the UI tooltip
    confidence_delta: float = 0.0  # adjustment to aggregate confidence

    @classmethod
    def skipped(cls, reason: str = "Verification disabled") -> "VerificationResult":
        return cls(status="skipped", reason=reason, confidence_delta=0.0)


def _parse_verification(raw: str) -> VerificationResult:
    """Parse the VLM response into a structured result."""
    text = raw.strip()
    upper = text.upper()

    if "VERIFIED:" in upper or upper.startswith("VERIFIED"):
        reason = text.split(":", 1)[1].strip() if ":" in text else "Answer is consistent with the imagery."
        return VerificationResult(status="verified", reason=reason, confidence_delta=0.05)

    if "UNCERTAIN:" in upper or upper.startswith("UNCERTAIN"):
        reason = text.split(":", 1)[1].strip() if ":" in text else "Answer may not be fully supported by the imagery."
        return VerificationResult(status="uncertain", reason=reason, confidence_delta=-0.1)

    # If the model wrote a sentence confirming or questioning the answer
    if any(pos in upper for pos in ("YES", "CORRECT", "ACCURATE", "SUPPORTED", "CONSISTENT")):
        return VerificationResult(status="verified", reason=text[:120], confidence_delta=0.05)

    return VerificationResult(
        status="uncertain",
        reason=text[:120] if text else "Verification response was ambiguous.",
        confidence_delta=-0.05,
    )


async def verify_answer(
    answer: str,
    images: List[bytes],
    vlm_backend: str = "gemini",
) -> VerificationResult:
    """
    Cross-check the proposed answer against the source imagery using a
    second VLM call.

    Returns a VerificationResult that the controller attaches to the
    QueryResult and trace.
    """
    from services.inference.vlm_gateway import vlm_call, vlm_available

    ok, reason = vlm_available(vlm_backend)
    if not ok:
        return VerificationResult.skipped(f"VLM unavailable: {reason}")

    if not images:
        return VerificationResult.skipped("No preview images available for verification.")

    instruction = (
        "You are a remote-sensing quality reviewer. You are shown satellite imagery "
        "and a proposed answer that was generated by an AI assistant.\n\n"
        f'Proposed Answer: "{answer}"\n\n'
        "Your task: verify whether the proposed answer is consistent with what the image actually shows.\n"
        "Respond with EXACTLY one of these two formats:\n"
        "VERIFIED: <one-line reason why the answer matches the evidence>\n"
        "UNCERTAIN: <one-line reason why the answer may be wrong or unsupported>"
    )

    try:
        out = await vlm_call(images, instruction, backend=vlm_backend)
        return _parse_verification(out.get("text", ""))
    except Exception as e:
        log.warning("Verification VLM call failed: %s", e)
        return VerificationResult.skipped(f"Verification call failed: {type(e).__name__}")
